Repository iDEA-org/iDEA, pull requests merged in 2023-07, with the labels that each got.

#17 Update non_interacting.py to improve speed
  iDEA/methods/non_interacting.py
Labels: enhancement, single particle

#16 Update non_interacting.py to fix duplicate states issue
  iDEA/methods/non_interacting.py
Labels: bug, single particle, PUSH TO PYPI, PUSH TO PAGES

#8 [WIP] Add Kohn-Sham Strictly Correlated Electrons method
  iDEA/__init__.py
  iDEA/methods/__init__.py
  iDEA/methods/kssce.py
  mods.yml
  tutorial/example_kssce.ipynb
Labels: enhancement, methods
